spring:
  jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/shop"
    username: admin
    password: admin

# Binding for HTTP front end
server:
  port: 8081
